// Create some realistic seed data so it looks like a real app instead of the bogus of Faker.JS

// Usernames
// Real names
// Topic titles
// Comments

export const seedData = {
  avatars: [
    'https://res.cloudinary.com/wipchad/image/upload/v1703416986/avatar_4_xl9pmt.jpg',
    'https://res.cloudinary.com/wipchad/image/upload/v1703416986/avatar_3_pfufgt.jpg',
    'https://res.cloudinary.com/wipchad/image/upload/v1703416986/avatar_1_ul7ay6.jpg',
    'https://res.cloudinary.com/wipchad/image/upload/v1703416986/avatar_2_ormtns.jpg',
    'https://res.cloudinary.com/wipchad/image/upload/v1703416986/avatar_5_q6i3ep.jpg',
    'https://res.cloudinary.com/wipchad/image/upload/v1703417083/avatar_6_zztbnc.jpg',
    'https://res.cloudinary.com/wipchad/image/upload/v1703417083/avatar_7_ulwvsc.jpg',
    'https://res.cloudinary.com/wipchad/image/upload/v1703417083/avatar_8_lnjofg.jpg',
    'https://res.cloudinary.com/wipchad/image/upload/v1703417083/avatar_9_oq2wgl.jpg',
    'https://res.cloudinary.com/wipchad/image/upload/v1703417083/avatar_11_mlhlt0.jpg',
    'https://res.cloudinary.com/wipchad/image/upload/v1703417083/avatar_10_nq6h7h.jpg',
    'https://res.cloudinary.com/wipchad/image/upload/v1703417084/avatar_12_z5ye0s.jpg',
    'https://res.cloudinary.com/wipchad/image/upload/v1703417084/avatar_13_gm6ekt.jpg',
    'https://res.cloudinary.com/wipchad/image/upload/v1703417084/avatar_14_lqytzx.jpg',
    'https://res.cloudinary.com/wipchad/image/upload/v1703417084/avatar_15_sthzob.jpg',
    'https://res.cloudinary.com/wipchad/image/upload/v1703417085/avatar_18_joryal.jpg',
    'https://res.cloudinary.com/wipchad/image/upload/v1703417085/avatar_17_ikdzd1.jpg',
    'https://res.cloudinary.com/wipchad/image/upload/v1703417085/avatar_20_ru8ztg.jpg',
    'https://res.cloudinary.com/wipchad/image/upload/v1703417085/avatar_19_b2xada.jpg',
  ],
  bios: [
    'Building the future of remote work at Nomadify 🌏, while globe-trotting. Part-time saxophonist 🎷.',
    'SaaS enthusiast. Just hit $50K MRR with my project, TaskEase 📈. Trail runner 🏞️ and sourdough baker 🍞.',
    'Bootstrapping my dream project, ArtiShop, a platform for artists. 🎨 Cat lover and vintage car collector. 🚗',
    '🚀 Launching my third startup, CodeBrew, a tool for developers. Chess fanatic and amateur astronomer 🔭.',
    'Digital marketer by day, indie game developer by night. Working on a puzzle game, MindTwist. 🧩 Yoga enthusiast 🧘.',
    'From corporate lawyer to tech founder. Creating LegalMind, a legaltech startup. Avid traveler and history buff. ✈️🏛️',
    'Educator turned app developer. Revolutionizing learning with EduFun. 📚 Love hiking and bird watching. 🦜',
    'Freelance designer, passionate about creating user-friendly experiences. Cycling around Europe 🚴‍♀️ while freelancing.',
    'Guitarist 🎸 and software engineer. Combining music and tech at TuneUp. Also a craft beer aficionado. 🍺',
    'Climbing the MRR mountain with ClimbTrack, an app for climbers. 🧗‍♂️ Always planning my next adventure trip. 🌍',
    'Healthcare worker turned coder. Developing HealthHub, a patient care app. Marathoner and plant-based diet advocate. 🌱🏃‍♀️',
    'Launching my first indie game, SpaceOdyssey. 🌌 Passionate about storytelling and VR experiences. 🕹️',
    'Creating mindful tech at ZenSpace, a meditation app. 🧘‍♂️ Nature photographer and environmentalist. 🌲',
    'Digital nomad, building a network of remote entrepreneurs. Currently in Bali 🌴. Surfing and drone photography are my jam. 🏄‍♂️📸',
    'Fintech rebel, working on disruptor bank NextGenFinance 💳. Love playing jazz piano 🎹 and brewing my own coffee. ☕️',
    'Proud founder of GreenEats, an app promoting sustainable dining. 🌿 Urban gardening enthusiast. 🌻',
    'Ex-journalist, now running a PR agency for tech startups. Marathon runner and poetry slammer. 🏃‍♂️🎤',
    'Reviving ancient languages through tech with LinguaRevive. Linguist and amateur archaeologist. 🏺',
    'Building AI-driven fitness at FitAI 🏋️‍♀️. Always up for a mountain biking challenge. 🚵‍♀️',
    'Creating a social impact with my startup, EcoAction. 🌍 Vegan and aspiring documentary filmmaker. 🎥',
    'Full-time coder, part-time DJ. Mixing tunes and code at BeatCoder. 🎛️ Love salsa dancing and spicy food. 🌶️',
    'Bridging art and technology at my startup, ArtTech. Sculptor and VR enthusiast. 🗿🕶️',
    'Just sold my first startup! 🚀 Now mentoring young entrepreneurs. Chess master and vintage book collector. 📚',
    'Building BreatheWell, an app for respiratory health. 🌬️ Free diving enthusiast and marine conservation volunteer. 🐠',
    'Ex-chef, now tech entrepreneur. Cooking up a foodie app, GourmetGo. Loves hiking and experimental cooking. 🥘🌲',
  ],

  todos: [
    'Watch a military helicopter maneuvering near the coastal town',
    'Restock on poultry supplies',
    'Reset the process queue',
    'Engage in gift packaging activities',
    'Resolve recent software issues post-update',
    'Implement version 2.0 of the software',
    'Configure automated testing and deployment via GitHub Actions',
    'Start a new project with Ruby on Rails and enhance existing scripts',
    'Improve web accessibility by adding alt text to images',
    'Address issues in the production environment and go live',
    'Exercise routine: Upper Body and Lower Back Training, 1 hour 7 minutes',
    'Discard unused UI library to streamline code',
    'Complete the video editing interface for a promotional tool',
    "Implement Tailwind CSS 'prose' for article formatting",
    'Get ready for a family gathering',
    'Release a new Carrd plugin across multiple platforms, details in provided links',
    'Enhance user onboarding communication and handle absence of data',
    'Revise the real estate website',
    'Cleanse email list for marketing purposes',
    'Incorporate article titles into webpage titles for SEO',
    'Optimize build process to reduce deployment time',
    'Acquire a Christmas tree',
    'Create Jira projects for personal app concepts',
    'Redirect short URLs to full-length blog URLs with IDs',
    'Enhance URL aesthetics with meaningful titles',
    'Generate unique IDs for blog articles',
    'Plan a family visit',
    'Take a scenic dog walk above the cloud line',
    'Progress on SwiftUI loader project',
    'Allocate time for a rejuvenating nap',
    'Display article titles on the homepage with a dedicated reading page',
    'Conduct tests using a work-in-progress bot',
    'Deploy a basic version of the blog to test custom domains',
    'Purchase fresh bakery items and coffee',
    'Enjoy a focused work session with coffee and a candle',
    'Coffee break',
    'Mark day 1088 of continuous startup projects',
    'Set up a new iPad for children, ensuring game data preservation',
    'Commit to a 28-minute morning walk',
    'Update server configurations for better authorization handling',
    'Resolve a critical authentication bug in the production environment',
    'Early coding session at 6 AM, continuing interview project and Swift learning',
    'Schedule a gym session',
    'Reflect on a night of insufficient sleep',
    'Engage in a strength training workout',
    'Plan a festive family dinner for Christmas',
    'Install a custom-built headphone amplifier',
    'Post a daily motivational reminder',
    "Read a passage from 'The Daily Stoic'",
    'Launch a personal blog',
    'Enjoy a relaxing Sunday',
    'Take a rest day',
    'Spend quality time during an extended holiday',
    'Celebrate Christmas early with grandmother',
    'Dedicate the day to family activities',
    'Integrate media pages into user and project profiles',
    'Configure DNS and analytics for a custom domain',
    'Optimize the photo AI landing page for efficient loading',
    'Celebrate the indexing of web pages',
    'Adjust job posting policies for major companies',
    'Draft legal documents for a new business venture',
    'Escape to the countryside for the holidays',
    'Design an attractive user interface button',
    'Acquire and troubleshoot a flight simulator joystick',
    'Enhance welcome page usability and add to the sidebar',
    "Celebrate a friend's birthday",
    'Develop an AI chatbot inspired by a renowned entrepreneur',
    'Compute and utilize average color for image placeholders',
    'Add new JavaScript utilities for job benefits section',
    'Plan a visit to an upscale dining establishment',
    'Experiment with the Web Audio APi',
  ],
}
